apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant-sample
spec:
  authorino:
    replicas: 3
    evaluatorCacheSize: 100
    metrics:
      deep: true
    tracing:
      endpoint: rpc://simplest-collector.observability.svc.cluster.local:4317
    volumes:
      items:
      - name: tracing-service-cert
        mountPath: /etc/ssl/certs
        configMaps:
        - tracing-service-cert
        items:
        - key: tracing-service.crt
          path: tracing-service.crt
