apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/toystore
  - ../../bases/kuadrant-operator
  - ../../bases/authPolicy
  - ../../bases/jaeger
patches:
  - kuadrant.yaml
