apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: jaeger
  name: jaeger-simplest-server-cert
spec:
  dnsNames:
  - simplest-collector.observability.svc
  - simplest-collector.observability.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: jaeger-ca
  secretName: jaeger-simplest-server-cert
